<?xml version = "1.0" ?>
<?xml-stylesheet type="text/xsl" href="L_ASMR.xsl"?>
<!DOCTYPE GRID [
  <!ELEMENT GRID (BANDS, COLUMNS, ROWS*)>
  <!ATTLIST GRID ExportVersion CDATA #REQUIRED>
  <!ELEMENT BANDS (BAND*)>
  <!ELEMENT BAND EMPTY>
  <!ATTLIST BAND Index CDATA #REQUIRED>
  <!ATTLIST BAND Caption CDATA #IMPLIED>
  <!ELEMENT COLUMNS (COLUMN*)>
  <!ELEMENT COLUMN EMPTY>
  <!ATTLIST COLUMN Name CDATA #REQUIRED>
  <!ATTLIST COLUMN Caption CDATA #IMPLIED>
  <!ATTLIST COLUMN Index CDATA #REQUIRED>
  <!ATTLIST COLUMN BandIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN RowIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN ColIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN Width CDATA #IMPLIED>
  <!ELEMENT GROUP (GROUP*, ROW*)>
  <!ATTLIST GROUP GroupText CDATA #IMPLIED>
  <!ELEMENT ROWS (ROW*)>
  <!ELEMENT ROW EMPTY>
  <!ATTLIST ROW Comment CDATA #IMPLIED>
  <!ATTLIST ROW Description CDATA #IMPLIED>
  <!ATTLIST ROW DataSheet CDATA #IMPLIED>
]>
<GRID ExportVersion="1.0">
  <BANDS>
    <BAND Index="0" Caption=""></BAND>
  </BANDS>
  <COLUMNS>
    <COLUMN Name="Comment" Caption="Comment" Index="0" BandIndex="0" RowIndex="0" ColIndex="0" Width="100"></COLUMN>
    <COLUMN Name="Description" Caption="Description" Index="1" BandIndex="0" RowIndex="0" ColIndex="1" Width="100"></COLUMN>
    <COLUMN Name="DataSheet" Caption="DataSheet" Index="2" BandIndex="0" RowIndex="0" ColIndex="2" Width="100"></COLUMN>
  </COLUMNS>
  <ROWS>
    <ROW Comment="OLED-12864" Description="Ecran LCD 0.96&#34; 128x64pix" DataSheet="https://www.vishay.com/docs/37902/oled128o064dbpp3n00000.pdf"></ROW>
    <ROW Comment="Jack_Femelle" Description="Prise Mini Jack St&#233;r&#233;o Femelle" DataSheet=""></ROW>
    <ROW Comment="WM-61A" Description="Microphone &#40;sur Header&#41;" DataSheet="https://components101.com/sites/default/files/component_datasheet/Electret&#37;20Condenser&#37;20Microphone.pdf"></ROW>
    <ROW Comment="Micro_SD" Description="Embase de Carte SD" DataSheet=""></ROW>
    <ROW Comment="Micro_USB" Description="Prise Micro USB Femelle" DataSheet=""></ROW>
    <ROW Comment="LM1117" Description="R&#233;gulateur de tension" DataSheet="http://www.farnell.com/datasheets/2019100.pdf"></ROW>
    <ROW Comment="OPA1654" Description="Quad Audio AmpliOp" DataSheet="http://www.ti.com/lit/ds/symlink/opa1654.pdf"></ROW>
    <ROW Comment="PCM3060" Description="St&#233;r&#233;o In/Out Audio Codec" DataSheet="http://www.ti.com/lit/ds/symlink/pcm3060.pdf"></ROW>
    <ROW Comment="PIC32MZ2048EFH064" Description="Micro-contr&#244;leur PIC32MZ" DataSheet="http://ww1.microchip.com/downloads/en/DeviceDoc/60001320D.pdf"></ROW>
    <ROW Comment="TP4056" Description="Adaptateur de charge USB vers Batterie" DataSheet="https://dlnmh9ip6v2uc.cloudfront.net/datasheets/Prototyping/TP4056.pdf"></ROW>
    <ROW Comment="USBLC6-2" Description="Protection_ESD" DataSheet="http://www.st.com/content/ccc/resource/technical/document/datasheet/06/1d/48/9c/6c/20/4a/b2/CD00050750.pdf/files/CD00050750.pdf/jcr:content/translations/en.CD00050750.pdf"></ROW>
  </ROWS>
</GRID>
